ml_utils:
  raw_data_file: depression_data.csv
  sample_data_file: depression_data_sample.csv
  sample_fraction: 0.05
  random_state: 123

ml_train:
  target: "history_of_mental_illness"
  random_seed: 123
  test_size: 0.25
  model_names: ['GLM', 'RF', 'XGB', 'LGBM']
  # model_names: ['GLM']
  model_params:
    GLM:
      classifier__C: [0.1, 1, 10]
      classifier__max_iter: [1000]
      classifier__penalty: ['l1', 'l2']
    RF:
      classifier__n_estimators: [20, 50, 100]
      classifier__max_depth: [10, 20]
    XGB:
      classifier__learning_rate: [0.1, 0.01]
      classifier__n_estimators: [50, 100, 150]
      classifier__max_depth: [10, 20]
    LGBM:
      classifier__learning_rate: [0.1, 0.01]
      classifier__n_estimators: [50, 100, 150]
      classifier__max_depth: [10, 20, 30]
      classifier__num_leaves: [20, 50, 100]
  model_save: True
  cv: 3
  scoring: roc_auc
  n_jobs: -1

genai_sentiment:
  llm_model_name: "gpt-3.5-turbo-instruct"
  temperature: 0